### PR TITLE
Add ToEntry on Collection

### PR DESCRIPTION
**Pull request by hooloovooo**

### CODE REVIEW

**Comment by hooloovooo** [comment]
Wops. Made some more changes to my fork and forgot i had this waiting here. I wouldn't merge this before i fix it.

**Comment by AlexRamey** [comment]
what's the status of this?

**Comment by AlexRamey** [comment]
@hooloovooo ?

**Comment by hooloovooo** [comment]
This pr is probably usable as is. It's not just the toEntry function, but the other addition makes sense if you ask me. It's not up to me to merge it tho.

**Pull request merged**
